version: '3.4'

services:

  ferramentariadb:
    container_name: ferramentariadb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=FerramentariaDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  application:
    container_name: application
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=ferramentariadb;Port=5432;Database=FerramentariaDB;User Id=admin;Password=admin1234"
    depends_on:
      - ferramentariadb
    ports:
      - "8002:80"

